#!/usr/bin/env python3
from __future__ import annotations

"""
UserPromptSubmit hook — suggest skills that match the user's message.

Reads ~/.claude/skill-triggers.json (generated by skill-trigger-gen.py)
and does fast substring matching. Nudges Claude when a skill likely applies
but wasn't explicitly invoked.
"""

import json
import os
import re
import sys
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import contextlib
from pathlib import Path

TRIGGERS_FILE = Path.home() / ".claude" / "skill-triggers.json"
SUGGEST_LOG = Path.home() / ".claude" / "skill-suggest-log.tsv"
PROMPT_CACHE = Path.home() / ".claude" / "last-prompt.txt"

# Don't suggest if user already invoked a skill
SKILL_INVOKE_RE = re.compile(r"^/", re.MULTILINE)


def normalize(text: str) -> str:
    """Lowercase, collapse whitespace, strip punctuation."""
    return re.sub(r"[^\w\s]", " ", text.lower()).strip()


def main():
    try:
        data = json.load(sys.stdin)
    except json.JSONDecodeError, EOFError:
        return

    prompt = data.get("prompt", "")
    if not prompt or len(prompt) < 4:
        return

    # Don't fire if user is already invoking a slash command
    if SKILL_INVOKE_RE.match(prompt.strip()):
        return

    if not TRIGGERS_FILE.exists():
        return

    try:
        triggers = json.load(TRIGGERS_FILE.open())
    except json.JSONDecodeError, OSError:
        return

    prompt_norm = normalize(prompt)
    matches = []

    for skill_name, phrases in triggers.items():
        for phrase in phrases:
            phrase_norm = normalize(phrase)
            # Skip very short triggers that would false-positive
            if len(phrase_norm) < 4:
                continue
            if phrase_norm in prompt_norm:
                matches.append((skill_name, phrase))
                break  # One match per skill is enough

    # Always cache the prompt for the learn hook to read
    with contextlib.suppress(OSError):
        PROMPT_CACHE.write_text(prompt[:500])

    if matches:
        ts = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
        # Log predictions (original format + Hebbian)
        try:
            with SUGGEST_LOG.open("a") as f:
                for name, phrase in matches:
                    f.write(f"{ts}\tsuggested\t{name}\t{phrase}\n")
        except OSError:
            pass
        try:
            from hebbian_nudge import log_nudge

            for name, _phrase in matches:
                log_nudge("priming", f"use-skill:{name}", prompt_snippet=prompt[:200])
        except Exception:
            pass

        suggestions = ", ".join(f'`/{name}` (matched: "{phrase}")' for name, phrase in matches)
        print(
            f"[skill-suggest] Possible skill match: {suggestions}. "
            "Consider invoking if relevant — the user shouldn't need to remember skill names."
        )


if __name__ == "__main__":
    main()
