export GOG_KEYRING_PASSWORD={{ op://Agents/sge746vsbefyi6pojwwodzu3o4/gog_keyring_password }}
export OURA_TOKEN={{ op://Agents/sge746vsbefyi6pojwwodzu3o4/oura_token }}
export ZHIPU_API_KEY={{ op://Agents/sge746vsbefyi6pojwwodzu3o4/zhipu_api_key }}
export MOONSHOT_API_KEY={{ op://Agents/sge746vsbefyi6pojwwodzu3o4/moonshot_api_key }}
export XAI_API_KEY={{ op://Agents/sge746vsbefyi6pojwwodzu3o4/xai_api_key }}
export OPENAI_API_KEY={{ op://Agents/sge746vsbefyi6pojwwodzu3o4/openai_api_key }}
export ANTHROPIC_API_KEY={{ op://Agents/sge746vsbefyi6pojwwodzu3o4/anthropic_api_key }}
export GOOGLE_API_KEY={{ op://Agents/sge746vsbefyi6pojwwodzu3o4/google_api_key }}
export PERPLEXITY_API_KEY={{ op://Agents/sge746vsbefyi6pojwwodzu3o4/perplexity_api_key }}
# OPENROUTER_API_KEY removed 2026-03-30 — quorum uses flat-rate CLIs only
export WECHAT2RSS_TOKEN={{ op://Agents/sge746vsbefyi6pojwwodzu3o4/wechat2rss_token }}
export EXA_API_KEY={{ op://Agents/sge746vsbefyi6pojwwodzu3o4/exa_api_key }}
export AUTH_TOKEN={{ op://Agents/sge746vsbefyi6pojwwodzu3o4/auth_token }}
export CT0={{ op://Agents/sge746vsbefyi6pojwwodzu3o4/ct0 }}
export TELEGRAM_BOT_TOKEN={{ op://Agents/sge746vsbefyi6pojwwodzu3o4/telegram_bot_token }}
export TELEGRAM_COMES_BOT_TOKEN={{ op://Agents/sge746vsbefyi6pojwwodzu3o4/telegram_comes_bot_token }}
export TELEGRAM_API_ID=2040
export TELEGRAM_API_HASH=b18441a1ff607e10a989891a5462e627
export GOOGLE_MAPS_API_KEY={{ op://Agents/iter-routes-gmaps-key/credential }}
