#!/usr/bin/env python3
import os
import time

mtime = os.path.getmtime(os.path.expanduser("~/notes/Tonus.md"))
age = time.time() - mtime
if age < 3600:
    print("recent")
elif age < 86400:
    print("stale")
else:
    print("very stale")
